const posts = [
    {
        id: 1,
        heading: "Exciting Job Opportunity",
        subheading: "Join Our Team Today!",
        description: "We're looking for talented individuals to join our dynamic team. If you're passionate about technology and innovation, apply now!",
        created_at: new Date().toISOString(),
    },
    {
        id: 2,
        heading: "Learn React Native",
        subheading: "Master Mobile Development",
        description: "Discover the power of React Native and build amazing mobile apps for iOS and Android platforms. Start your journey today!",
        created_at: new Date().toISOString(),
    },
    {
        id: 3,
        heading: "Remote Work Opportunities",
        subheading: "Work from Anywhere!",
        description: "Explore remote work opportunities and enjoy the flexibility of working from the comfort of your home. Join our remote team now!",
        created_at: new Date().toISOString(),
    },
    {
        id: 4,
        heading: "Exciting Career Growth",
        subheading: "Advance Your Career",
        description: "Unlock new opportunities for career growth and development. Join our team and take your career to the next level!",
        created_at: new Date().toISOString(),
    },
    {
        id: 5,
        heading: "Join Our Community",
        subheading: "Connect with Professionals",
        description: "Become part of our vibrant community and network with industry professionals. Join us today and expand your network!",
        created_at: new Date().toISOString(),
    },
    // Add 20 more posts
    {
        id: 6,
        heading: "New Product Launch",
        subheading: "Discover Innovation",
        description: "Be the first to experience our latest product launch. Explore cutting-edge features and functionalities. Get started now!",
        created_at: new Date().toISOString(),
    },
    {
        id: 7,
        heading: "Exciting Internship Opportunity",
        subheading: "Gain Valuable Experience",
        description: "Kickstart your career with our exciting internship program. Gain hands-on experience and valuable skills. Apply now!",
        created_at: new Date().toISOString(),
    },
    {
        id: 8,
        heading: "Web Development Bootcamp",
        subheading: "Become a Web Developer",
        description: "Embark on a journey to become a proficient web developer. Join our comprehensive bootcamp and master web development!",
        created_at: new Date().toISOString(),
    },
    {
        id: 9,
        heading: "Digital Marketing Seminar",
        subheading: "Boost Your Marketing Skills",
        description: "Learn the latest trends and strategies in digital marketing. Attend our seminar and enhance your marketing skills!",
        created_at: new Date().toISOString(),
    },
    {
        id: 10,
        heading: "Exciting Design Contest",
        subheading: "Showcase Your Creativity",
        description: "Calling all designers! Participate in our design contest and showcase your creativity to the world. Don't miss this opportunity!",
        created_at: new Date().toISOString(),
    },
    {
        id: 11,
        heading: "Mobile App Development Workshop",
        subheading: "Build Innovative Apps",
        description: "Join our workshop and learn the essentials of mobile app development. Turn your ideas into reality and build innovative apps!",
        created_at: new Date().toISOString(),
    },
    {
        id: 12,
        heading: "Exciting Career Opportunities in Tech",
        subheading: "Explore Tech Careers",
        description: "Discover exciting career opportunities in the tech industry. Explore diverse roles and find your dream job in tech!",
        created_at: new Date().toISOString(),
    },
    {
        id: 13,
        heading: "Data Science Bootcamp",
        subheading: "Master Data Analytics",
        description: "Become a data science expert with our intensive bootcamp. Master data analytics and unlock new career opportunities!",
        created_at: new Date().toISOString(),
    },
    {
        id: 14,
        heading: "Exciting Hackathon Event",
        subheading: "Showcase Your Skills",
        description: "Join our hackathon event and showcase your coding skills. Collaborate with like-minded individuals and build innovative solutions!",
        created_at: new Date().toISOString(),
    },
    {
        id: 15,
        heading: "Social Media Marketing Workshop",
        subheading: "Boost Your Social Presence",
        description: "Learn the art of social media marketing and enhance your social presence. Join our workshop and become a social media expert!",
        created_at: new Date().toISOString(),
    },
    {
        id: 16,
        heading: "Cybersecurity Conference",
        subheading: "Stay Secure Online",
        description: "Stay updated on the latest cybersecurity trends and practices. Attend our conference and learn how to stay secure online!",
        created_at: new Date().toISOString(),
    },
    {
        id: 17,
        heading: "Machine Learning Seminar",
        subheading: "Explore AI Technologies",
        description: "Discover the power of machine learning and explore AI technologies. Join our seminar and dive into the world of AI!",
        created_at: new Date().toISOString(),
    },
    {
        id: 18,
        heading: "Digital Transformation Summit",
        subheading: "Embrace Digital Innovation",
        description: "Learn how to embrace digital innovation and drive business growth. Attend our summit and unlock the potential of digital transformation!",
        created_at: new Date().toISOString(),
    },
    {
        id: 19,
        heading: "Product Management Workshop",
        subheading: "Become a Product Leader",
        description: "Unlock the secrets of successful product management. Join our workshop and become a product leader in your industry!",
        created_at: new Date().toISOString(),
    },
    {
        id: 20,
        heading: "Cloud Computing Bootcamp",
        subheading: "Master Cloud Technologies",
        description: "Become proficient in cloud computing technologies. Join our bootcamp and master the essentials of cloud computing!",
        created_at: new Date().toISOString(),
    },
    {
        id: 21,
        heading: "UX/UI Design Workshop",
        subheading: "Create Stunning Designs",
        description: "Learn the principles of UX/UI design and create stunning user interfaces. Join our workshop and become a design expert!",
        created_at: new Date().toISOString(),
    },
    {
        id: 22,
        heading: "Blockchain Conference",
        subheading: "Explore Blockchain Technology",
        description: "Discover the potential of blockchain technology and its impact on various industries. Attend our conference and dive deep into blockchain!",
        created_at: new Date().toISOString(),
    },
    {
        id: 23,
        heading: "Artificial Intelligence Summit",
        subheading: "Unlock AI Opportunities",
        description: "Unlock new opportunities in artificial intelligence. Join our summit and learn how AI is shaping the future!",
        created_at: new Date().toISOString(),
    },
    {
        id: 24,
        heading: "Software Engineering Bootcamp",
        subheading: "Become a Software Engineer",
        description: "Embark on a journey to become a skilled software engineer. Join our bootcamp and master software development!",
        created_at: new Date().toISOString(),
    },
    {
        id: 25,
        heading: "Tech Startup Incubator Program",
        subheading: "Launch Your Startup",
        description: "Transform your innovative ideas into successful startups. Join our incubator program and kickstart your entrepreneurial journey!",
        created_at: new Date().toISOString(),
    },
];

export default posts;
